# Generated by Django 6.0.5 on 2026-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taster",
            name="favorite_beverages",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_by",
                to="catalog.beverage",
                verbose_name="Favorite Beverages",
            ),
        ),
    ]
